### ISSUE TITLE
[request] Changing the auto-announce

### ISSUE THREAD

**Issue by waytoomuchgaming** [Road-block/CallToArms#2]
From "LFM: xxxxx (1/5) > For more info type '/w xxx details" to "LF*M: xxxxx > For more info type '/w xxx details", where * is the missing number to complete the group. Even better, when alone, instead of "LF4M", put "LFG".

**Comment by Road-block** [comment]
I can do the first one.  
For the second one I'm not sure that's a good idea.  


When a person is doing LFM - even as the first (and still) single - groupmember it tells they are prepared to keep searching for and adding members until the group is complete.  


LFG on the other hand I'd take as meaning that someone is looking to join a partially filled group and doesn't care about forming it themselves.

**Comment by waytoomuchgaming** [comment]
Ok.
I never saw the LFG/LFM used that way, in all the years i played. Usually, when someone alone use LFM, it's considered a trick to lure people in empty groups, which lead to suspicion (if he's lying about that, what else nefarious can he do ?).
So i prefer to avoid that. Can we have it as an option ?

**Comment by Road-block** [comment]
That might be a concern for a vague LFM, but how is that possible when the group size is there in the message.  
It's immediately obvious that the person is looking to "start a group".

**Comment by waytoomuchgaming** [comment]
In that case, yes. LF4M is honest, LFM when you are alone is not ^^
As long as people get all the information they need, in a easy way to understand, i'm good with anything.
